
title: "Catherine Jörg"
url: "http://catherinejorg.ch/"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

exclude: [ "CNAME", "README.md", "Gemfile", "Gemfile.lock" ]

gems:
  - jekyll-sitemap

